### ISSUE TITLE
Chrome Ctrl-lock

### ISSUE THREAD

**Issue by aareman** [lordm/vim-browser-reload-linux#15]
On chrome reload start, whenever I save ctrl lock gets set. This really busts up things since its not clear what gets rid of it. in vim pressing ctrl seems to remove it. Why would this plugin be setting that?

I'm on ubuntu 18, using neovim 0.4

**Comment by jaywilliams** [comment]
Having CTRL or another meta key held down in Vim is a nightmare...

**Comment by lordm** [comment]
Thanks @aareman and @jaywilliams for digging this up.
