### ISSUE TITLE
autoreload not work

### ISSUE THREAD

**Issue by v6cc** [lordm/vim-browser-reload-linux#18]
Does this plugin work on nvim? 

I use nvim and chrome in fedora31 but autoload sometimes doesn't work. 

And  :chromereload needs to be executed twice.
The first time it seems that the browser is the reload but the content is the same. 
The second time it displays the new content.

**Comment by zdmgmail** [comment]
I tried   nnoremap S :w<CR>:ChromeReload<cr>:ChromeReload<cr>  but also need twice

**Comment by zdmgmail** [comment]
I tried nnoremap S :w<cr>:ChromeReload<cr>:ChromeReload<cr>  but also need twice

**Comment by zdmgmail** [comment]
[](url)file:///home/zdm/Pictures/03-20_18:29:20.png

**Comment by zdmgmail** [comment]
[](file:///home/zdm/Pictures/03-20_18:29:20.png)

this also need twice
