### ISSUE TITLE
Not working with chrome

### ISSUE THREAD

**Issue by GCorbel** [lordm/vim-browser-reload-linux#9]
I have Ubuntu 14.04 with Chromium-browser 34. When I use `:ChromeReload` it does nothing.  I tried some things with xdotool : 

```
 xdotool search --onlyvisible --name chromium # return an id
 xdotool search --onlyvisible --name chromium-browser # return nothing
 xdotool search --onlyvisible --name chromium key --clearmodifiers ctrl+r # do nothing
```

Thanks for your work!

**Comment by GCorbel** [comment]
1 year later, I found the solution. I works without those lines : 

https://github.com/lordm/vim-browser-reload-linux/blob/master/plugin/browser-reload-linux.vim#L20-L22

I can do a pull request but I have to know why it theese lines can be useful. Can you give me some help?

**Comment by lordm** [comment]
I apologize to you for not looking on this issue. I don't know how I didn't notice it last year. 
As far as i remember there was a problem with windowactivate and setting the focus on chrome. I'm not sure why it doesn't work for you. It's working with my chrome here.
If you want do a pull request and modify as you see fit, and I'll test on my side too.

**Comment by GCorbel** [comment]
No problem! I did the pull request.
